version: "3.4"

services:
  mysql:
    container_name: rbac-mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - mysql:/var/lib/mysql/
      - ./sql/rbac_init.sql:/docker-entrypoint-initdb.d/rbac_init.sql:ro
  
  redis:
    container_name: rbac-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  server:
    container_name: rbac-server
    build:
      context: ./rbac-server/
    image: rbac-server
    restart: unless-stopped
    ports:
      - "28080:28080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS:
        ${JAVA_OPTS:-
          -Xms512m
          -Xmx512m
          -Djava.security.egd=file:/dev/./urandom
        }
      ARGS:
        --spring.datasource.url=${DATASOURCE_URL:-jdbc:mysql://rbac-mysql:3306/rbac?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.username=${DATASOURCE_USERNAME:-root}
        --spring.datasource.password=${DATASOURCE_PASSWORD:-123456}
        --spring.redis.host=${REDIS_HOST:-rbac-redis}
    depends_on:
      - mysql
      - redis

  web:
    container_name: my-admin-project
    build:
      context: ./my-admin-project
      args:
        NODE_ENV:
          ENV=${NODE_ENV:-production}
          VUE_APP_TITLE=${VUE_APP_TITLE:-RBAC管理系统}
    image: my-admin-project
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mysql:
    driver: local
  redis:
    driver: local
