server:
  port: 28080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost  # Redis服务器地址
    port: 6379       # Redis服务器端口
    password:        # Redis服务器密码，如果有的话
    jedis:
      pool:
        max-active: 10    # 连接池最大连接数
        max-idle: 5       # 连接池中的最大空闲连接
        min-idle: 1       # 连接池中的最小空闲连接
        max-wait: 10000ms # 连接池最大阻塞等待时间


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo

jwt:
  secret: lHa9INNoyReLwEI1JDWUQKfIgTCjrTrI60xWQCRz8nogNIPJKHAtIVjthfC+QBfhYUk/ci4F6uuK8VI5/VRfx+yHUNLBqMild3EJIvjo2qbe7B+5WgrUa14CepbPgjCX3vWKw9WeBbTrpxTZ2GaYecSdz/ufSObX4X+IsOM/2t8tGYyc0184AjSZwbV/mlCkGHA0uHiV/Hu3I83ePY1FSuyPQhSNqG+wfgjIX2ykeHjGr7U4pt1ehuY+/2PRQNZlR0heN9wbglTPyChczkvAWdsCnVd6i0Wi1gMa6IBe1ZOc7Fy2jy2JVKWbfg/4fRWQnnGmiLfqjFkoXjiK/WOW3g==
  access_token:
    expiration: 3600 # in seconds
  refresh_token:
    expiration: 604800 # in seconds
